
title: MW-NeRF
description: Multi-Wavelength NeRF Models for Spacecraft Modeling in Shadowed Environments
theme: minima
plugins:
  - jekyll-seo-tag

baseurl: "https://github.com/Logggy/MW-NeRF-Project/tree/main" 
